# Fuego contra Fuego

Instalamos, cargamos y seteamos el entorno

In [ ]:
#%pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.5)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 6.7 MB/s eta 0:00:00
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 6.1 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.19.1 colorlog-6.12.0 optuna-4.9.0

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from tqdm.notebook import tqdm

from sklearn.tree import DecisionTreeClassifier, plot_tree,  _tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import ShuffleSplit, StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

from joblib import Parallel, delayed

import optuna
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_slice, plot_contour

from time import time

import pickle

c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## DATA BASE

In [2]:
base_path = "/Users/carof/Downloads/DENICOLAY/"
dataset_path = base_path 
modelos_path = base_path + 'modelos/'
db_path = base_path + 'data/'
dataset_file = 'competencia_01.csv'

ganancia_acierto = 1_072_500
costo_estimulo = 27_500

mes_train = 202103
mes_test = 202105

# agregue sus semillas
semilla = 42
semillas = np.random.choice(1000000, size=50, replace=False).tolist()

data = pd.read_csv(dataset_path + dataset_file)

Seguimos trabajando con Marzo como entrenamiento y Mayo como test.

In [3]:
X = data[data['foto_mes'] == mes_train]
y = X['clase_ternaria']
X = X.drop(columns=['clase_ternaria'])

In [4]:
X_futuro = data[data['foto_mes'] == mes_test]
y_futuro = X_futuro['clase_ternaria']
X_futuro = X_futuro.drop(columns=['clase_ternaria'])

Y variaremos la forma de la función de ganancia, para poder ser utilizada de una forma más genérica.

In [ ]:
def ganancia_prob(y_hat, y, prop=1, class_index=1, threshold=0.025):
  @np.vectorize
  def ganancia_row(predicted, actual, threshold=0.025):
    return  (predicted >= threshold) * (ganancia_acierto if actual == "BAJA+2" else -costo_estimulo)

  return ganancia_row(y_hat[:,class_index], y).sum() / prop

Entrenemos y recordemos cuanto nos daba la ganancia en **Mayo**

Hablemos de ensemables, qué son?

* Un ensemble de modelos es una técnica donde se combinan múltiples modelos individuales para mejorar la precisión y robustez de las predicciones. La idea es que al combinar varios modelos, se pueden aprovechar las fortalezas de cada uno y reducir la posibilidad de errores que podría cometer un único modelo.

**Tipos de ensemble**:
 * **Bagging (Bootstrap Aggregating)**: Consiste en entrenar varios modelos base en diferentes subconjuntos del conjunto de datos de entrenamiento obtenidos mediante técnicas de remuestreo como el bootstrap y luego promediar sus predicciones. Ejemplo: **Random Forest**
 * **Boosting**: En esta técnica, los modelos se entrenan de manera secuencial. Cada modelo intenta corregir los errores cometidos por el modelo anterior. Ejemplo: AdaBoost y **Gradient Boosting**.
 * **Stacking**: En el stacking, se entrenan varios modelos y se combinan usando un "modelo meta". Las predicciones de los modelos base sirven como features para entrenar este modelo meta, que produce la predicción final.

* **Ventajas de usar ensemble de modelos**:
 * **Mejor rendimiento**: Al combinar modelos, generalmente se mejora la precisión en comparación con un solo modelo.
 * **Robustez**: Al integrar diferentes modelos, se mitiga el riesgo de que los errores de un modelo individual afecten gravemente la predicción final.

Pongamos foco en el **Random Forest**

Es un algoritmo de aprendizaje automático que funciona creando un conjunto de árboles de decisión. Para la creación de **árboles distintos** utiliza una técnica llamada bagging para crear múltiples subconjuntos del conjunto de datos de entrenamiento. Cada subconjunto se genera seleccionando al azar muestras del conjunto de datos original con reemplazo. No usa la totalidad de los datos de entrenamiento para cada conjunto. Los datos que quedan fueran son conocidos como **Out of Bag (oob)**

Para cada subconjunto, se construye un árbol de decisión. Sin embargo en cada nodo del árbol, **Random Forest** selecciona de forma aleatoria un grupo de variables y ajusta el árbol con esas variables. Este proceso ayuda a crear árboles que son menos correlacionados entre sí.

Cada árbol en el bosque se entrena de manera independiente usando su respectivo subconjunto de datos. Lueago, para una nueva observación, cada árbol realiza una predicción. El Random Forest luego combina las predicciones de todos los árboles para hacer una predicción final, devolviendo el promedio de las probabilidades de cada árbol individual.

Como desde la clase pasada solo personas más inteligentes, no vamos a empezar a probar **Random Forest** simples. Vamos a parametrizarlo desde el vamos.

Primero vamos a entender algunas limitaciones de la implementación:

El **Random Forest** no soporta nulos! Shame on you sklearn!.

Vamos a tener que imputar los datos. Discutamos entre todos forma de imputar los datos, mientras para salir del paso usamos la peor de todas.

In [6]:
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
Xi = imp_median.fit_transform(X)
Xif = imp_median.fit_transform(X_futuro)

Los parámetros que se pueden ajustar en el **rf** son

1. **n_estimators**: Número de árboles en el bosque.
2. **max_depth**: Profundidad máxima de los árboles.
3. **min_samples_split**: Número mínimo de muestras requeridas para dividir un nodo interno.
4. **min_samples_leaf**: Número mínimo de muestras requeridas para estar en un nodo hoja.
5. **max_features**: Número de features a usar en cada árbol. **sqrt** es una elección histórica.
6. **max_leaf_nodes**: Número máximo de nodos hoja en cada árbol.
7. **oob_score**: Indica si se usa la muestra fuera de bolsa (out-of-bag) para estimar la calidad del modelo. Para evitar hacer un **montecarlo-cross-validation** que se toma su tiempo, usaremos esta opción para buscar el mejor modelo. No es la mejor opción. Pero no es tan mala.
8. **n_jobs**: Siempre -1, para que use todos los cores presentes en 
9. **max_samples**: Fracción de los samples.

Finalmente nuestra función de optimización queda la siguiente forma:

In [13]:
def objective(trial):
    max_depth = trial.suggest_int('max_depth', 2, 32)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 2000)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 200)
    max_features = trial.suggest_float('max_features', 0.05, 0.7)

    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

    model.fit(Xi, y)

    return ganancia_prob(model.oob_decision_function_, y)

storage_name = "sqlite:////Users/carof/Downloads/DENICOLAY/optimization_rf.db"
study_name = "exp_401_random-forest-opt"

study = optuna.create_study(
    direction="maximize",
    study_name=study_name,
    storage=storage_name,
    load_if_exists=True,
)

[I 2026-09-07 16:58:06,910] A new study created in RDB with name: exp_401_random-forest-opt

### Primera optimizacion

In [ ]:
#study.optimize(objective, n_trials=100)

[I 2026-09-07 16:59:37,342] Trial 0 finished with value: 325902500.0 and parameters: {'max_depth': 30, 'min_samples_split': 1172, 'min_samples_leaf': 158, 'max_features': 0.47705155260923787}. Best is trial 0 with value: 325902500.0.
[I 2026-09-07 17:02:18,386] Trial 1 finished with value: 341495000.0 and parameters: {'max_depth': 14, 'min_samples_split': 490, 'min_samples_leaf': 169, 'max_features': 0.5804393957922185}. Best is trial 1 with value: 341495000.0.
[I 2026-09-07 17:13:26,320] Trial 2 finished with value: 337562500.0 and parameters: {'max_depth': 17, 'min_samples_split': 898, 'min_samples_leaf': 43, 'max_features': 0.5776010248361468}. Best is trial 1 with value: 341495000.0.
[I 2026-09-07 17:14:57,019] Trial 3 finished with value: 302885000.0 and parameters: {'max_depth': 5, 'min_samples_split': 152, 'min_samples_leaf': 121, 'max_features': 0.28844064612703657}. Best is trial 1 with value: 341495000.0.
[I 2026-09-07 17:18:22,171] Trial 4 finished with value: 346197500.0 and parameters: {'max_depth': 32, 'min_samples_split': 315, 'min_samples_leaf': 145, 'max_features': 0.337085376231711}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:20:35,450] Trial 5 finished with value: 341825000.0 and parameters: {'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 173, 'max_features': 0.5099269433065007}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:21:18,365] Trial 6 finished with value: 328735000.0 and parameters: {'max_depth': 14, 'min_samples_split': 1237, 'min_samples_leaf': 75, 'max_features': 0.4501373474235592}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:21:34,228] Trial 7 finished with value: 285450000.0 and parameters: {'max_depth': 4, 'min_samples_split': 1251, 'min_samples_leaf': 171, 'max_features': 0.3233654763697369}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:22:34,572] Trial 8 finished with value: 331595000.0 and parameters: {'max_depth': 19, 'min_samples_split': 845, 'min_samples_leaf': 68, 'max_features': 0.515620943474469}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:23:23,050] Trial 9 finished with value: 335692500.0 and parameters: {'max_depth': 31, 'min_samples_split': 437, 'min_samples_leaf': 76, 'max_features': 0.32486670181653915}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:23:41,140] Trial 10 finished with value: 285450000.0 and parameters: {'max_depth': 24, 'min_samples_split': 1994, 'min_samples_leaf': 5, 'max_features': 0.07675829084573121}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:25:09,881] Trial 11 finished with value: 343750000.0 and parameters: {'max_depth': 25, 'min_samples_split': 37, 'min_samples_leaf': 130, 'max_features': 0.6723672876263479}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:26:45,881] Trial 12 finished with value: 341550000.0 and parameters: {'max_depth': 26, 'min_samples_split': 413, 'min_samples_leaf': 122, 'max_features': 0.6957547429998554}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:27:03,144] Trial 13 finished with value: 320650000.0 and parameters: {'max_depth': 32, 'min_samples_split': 237, 'min_samples_leaf': 127, 'max_features': 0.07052132761010849}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:27:34,933] Trial 14 finished with value: 325077500.0 and parameters: {'max_depth': 22, 'min_samples_split': 665, 'min_samples_leaf': 196, 'max_features': 0.220101065982223}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:29:12,067] Trial 15 finished with value: 340917500.0 and parameters: {'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 140, 'max_features': 0.6992956686977608}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:29:47,204] Trial 16 finished with value: 342485000.0 and parameters: {'max_depth': 21, 'min_samples_split': 263, 'min_samples_leaf': 104, 'max_features': 0.18941166056002318}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:30:52,499] Trial 17 finished with value: 334372500.0 and parameters: {'max_depth': 28, 'min_samples_split': 668, 'min_samples_leaf': 97, 'max_features': 0.4030169457940589}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:31:58,567] Trial 18 finished with value: 305277500.0 and parameters: {'max_depth': 10, 'min_samples_split': 1945, 'min_samples_leaf': 146, 'max_features': 0.6182524152869443}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:32:48,280] Trial 19 finished with value: 298732500.0 and parameters: {'max_depth': 28, 'min_samples_split': 1601, 'min_samples_leaf': 193, 'max_features': 0.3967273049169901}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:33:15,154] Trial 20 finished with value: 338277500.0 and parameters: {'max_depth': 32, 'min_samples_split': 251, 'min_samples_leaf': 107, 'max_features': 0.16609393625018043}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:33:41,789] Trial 21 finished with value: 338167500.0 and parameters: {'max_depth': 22, 'min_samples_split': 322, 'min_samples_leaf': 99, 'max_features': 0.15985698583098995}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:34:15,761] Trial 22 finished with value: 331375000.0 and parameters: {'max_depth': 20, 'min_samples_split': 610, 'min_samples_leaf': 140, 'max_features': 0.23567868784986273}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:34:42,594] Trial 23 finished with value: 329615000.0 and parameters: {'max_depth': 23, 'min_samples_split': 143, 'min_samples_leaf': 105, 'max_features': 0.14887492064363514}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:35:38,106] Trial 24 finished with value: 342430000.0 and parameters: {'max_depth': 17, 'min_samples_split': 103, 'min_samples_leaf': 53, 'max_features': 0.381501920318301}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:36:10,726] Trial 25 finished with value: 344575000.0 and parameters: {'max_depth': 27, 'min_samples_split': 332, 'min_samples_leaf': 86, 'max_features': 0.20150320896241988}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:36:53,769] Trial 26 finished with value: 336407500.0 and parameters: {'max_depth': 27, 'min_samples_split': 537, 'min_samples_leaf': 33, 'max_features': 0.26597861827785174}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:37:14,379] Trial 27 finished with value: 316387500.0 and parameters: {'max_depth': 30, 'min_samples_split': 899, 'min_samples_leaf': 87, 'max_features': 0.10726989421865013}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:38:00,207] Trial 28 finished with value: 339982500.0 and parameters: {'max_depth': 29, 'min_samples_split': 349, 'min_samples_leaf': 151, 'max_features': 0.3338339032622837}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:38:57,707] Trial 29 finished with value: 340587500.0 and parameters: {'max_depth': 25, 'min_samples_split': 768, 'min_samples_leaf': 132, 'max_features': 0.4464136826260747}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:40:16,062] Trial 30 finished with value: 332557500.0 and parameters: {'max_depth': 26, 'min_samples_split': 1018, 'min_samples_leaf': 160, 'max_features': 0.6313951914549573}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:40:45,390] Trial 31 finished with value: 334015000.0 and parameters: {'max_depth': 21, 'min_samples_split': 233, 'min_samples_leaf': 119, 'max_features': 0.2006828954335914}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:41:08,915] Trial 32 finished with value: 316002500.0 and parameters: {'max_depth': 30, 'min_samples_split': 520, 'min_samples_leaf': 113, 'max_features': 0.13180108805320698}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:41:41,513] Trial 33 finished with value: 337892500.0 and parameters: {'max_depth': 17, 'min_samples_split': 314, 'min_samples_leaf': 89, 'max_features': 0.1961143034729157}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:42:20,458] Trial 34 finished with value: 340587500.0 and parameters: {'max_depth': 19, 'min_samples_split': 147, 'min_samples_leaf': 160, 'max_features': 0.2724508701967855}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:42:42,786] Trial 35 finished with value: 323592500.0 and parameters: {'max_depth': 24, 'min_samples_split': 456, 'min_samples_leaf': 58, 'max_features': 0.11225193486873747}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:50:32,388] Trial 36 finished with value: 336572500.0 and parameters: {'max_depth': 14, 'min_samples_split': 62, 'min_samples_leaf': 87, 'max_features': 0.5461303116655174}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:51:02,091] Trial 37 finished with value: 334592500.0 and parameters: {'max_depth': 26, 'min_samples_split': 240, 'min_samples_leaf': 180, 'max_features': 0.23533378180025444}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:51:26,223] Trial 38 finished with value: 326370000.0 and parameters: {'max_depth': 8, 'min_samples_split': 391, 'min_samples_leaf': 134, 'max_features': 0.3066896295841666}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:52:04,581] Trial 39 finished with value: 340065000.0 and parameters: {'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 115, 'max_features': 0.3491593776827283}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:52:17,636] Trial 40 finished with value: 249150000.0 and parameters: {'max_depth': 2, 'min_samples_split': 573, 'min_samples_leaf': 75, 'max_features': 0.4706077395935435}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:52:57,442] Trial 41 finished with value: 345730000.0 and parameters: {'max_depth': 16, 'min_samples_split': 116, 'min_samples_leaf': 45, 'max_features': 0.3814389219717938}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:53:43,503] Trial 42 finished with value: 338882500.0 and parameters: {'max_depth': 16, 'min_samples_split': 224, 'min_samples_leaf': 26, 'max_features': 0.43910639408271424}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:54:11,953] Trial 43 finished with value: 337452500.0 and parameters: {'max_depth': 15, 'min_samples_split': 119, 'min_samples_leaf': 62, 'max_features': 0.26914807039093525}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:54:56,331] Trial 44 finished with value: 313115000.0 and parameters: {'max_depth': 12, 'min_samples_split': 357, 'min_samples_leaf': 5, 'max_features': 0.5124825241428175}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:55:38,436] Trial 45 finished with value: 340835000.0 and parameters: {'max_depth': 20, 'min_samples_split': 182, 'min_samples_leaf': 34, 'max_features': 0.3628431591933918}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:55:51,081] Trial 46 finished with value: 321585000.0 and parameters: {'max_depth': 24, 'min_samples_split': 71, 'min_samples_leaf': 20, 'max_features': 0.054485420059946}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:56:21,022] Trial 47 finished with value: 336462500.0 and parameters: {'max_depth': 18, 'min_samples_split': 475, 'min_samples_leaf': 125, 'max_features': 0.29518114160745224}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:57:05,990] Trial 48 finished with value: 339900000.0 and parameters: {'max_depth': 12, 'min_samples_split': 293, 'min_samples_leaf': 151, 'max_features': 0.5611188057364024}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:58:12,438] Trial 49 finished with value: 332447500.0 and parameters: {'max_depth': 32, 'min_samples_split': 737, 'min_samples_leaf': 80, 'max_features': 0.666392321268648}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:59:06,869] Trial 50 finished with value: 335582500.0 and parameters: {'max_depth': 22, 'min_samples_split': 408, 'min_samples_leaf': 41, 'max_features': 0.42073318590508}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 17:59:45,270] Trial 51 finished with value: 341192500.0 and parameters: {'max_depth': 18, 'min_samples_split': 170, 'min_samples_leaf': 101, 'max_features': 0.38350378053512935}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:00:34,277] Trial 52 finished with value: 344657500.0 and parameters: {'max_depth': 16, 'min_samples_split': 101, 'min_samples_leaf': 51, 'max_features': 0.47650198877175487}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:01:16,368] Trial 53 finished with value: 337947500.0 and parameters: {'max_depth': 12, 'min_samples_split': 63, 'min_samples_leaf': 50, 'max_features': 0.4860007431946388}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:01:39,346] Trial 54 finished with value: 342512500.0 and parameters: {'max_depth': 15, 'min_samples_split': 277, 'min_samples_leaf': 47, 'max_features': 0.185296223787245}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:02:16,624] Trial 55 finished with value: 336655000.0 and parameters: {'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 68, 'max_features': 0.6158207449359026}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:03:12,443] Trial 56 finished with value: 319357500.0 and parameters: {'max_depth': 15, 'min_samples_split': 187, 'min_samples_leaf': 16, 'max_features': 0.5309281121262488}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:03:37,748] Trial 57 finished with value: 300932500.0 and parameters: {'max_depth': 13, 'min_samples_split': 1375, 'min_samples_leaf': 46, 'max_features': 0.24465779002904617}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:04:21,802] Trial 58 finished with value: 339102500.0 and parameters: {'max_depth': 16, 'min_samples_split': 297, 'min_samples_leaf': 41, 'max_features': 0.41041282204460994}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:04:46,933] Trial 59 finished with value: 345895000.0 and parameters: {'max_depth': 9, 'min_samples_split': 91, 'min_samples_leaf': 65, 'max_features': 0.3186924903684022}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:05:04,197] Trial 60 finished with value: 308907500.0 and parameters: {'max_depth': 5, 'min_samples_split': 73, 'min_samples_leaf': 67, 'max_features': 0.31420822169300755}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:05:30,140] Trial 61 finished with value: 341330000.0 and parameters: {'max_depth': 9, 'min_samples_split': 119, 'min_samples_leaf': 61, 'max_features': 0.34209196577613793}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:06:13,322] Trial 62 finished with value: 332447500.0 and parameters: {'max_depth': 10, 'min_samples_split': 195, 'min_samples_leaf': 36, 'max_features': 0.5896939007670426}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:06:28,099] Trial 63 finished with value: 313280000.0 and parameters: {'max_depth': 7, 'min_samples_split': 375, 'min_samples_leaf': 53, 'max_features': 0.17223111549702247}. Best is trial 4 with value: 346197500.0.
[I 2026-09-07 18:06:52,500] Trial 64 finished with value: 350377500.0 and parameters: {'max_depth': 31, 'min_samples_split': 291, 'min_samples_leaf': 47, 'max_features': 0.21527771890295355}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:07:32,755] Trial 65 finished with value: 349305000.0 and parameters: {'max_depth': 28, 'min_samples_split': 448, 'min_samples_leaf': 68, 'max_features': 0.3672685343939388}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:08:10,407] Trial 66 finished with value: 333685000.0 and parameters: {'max_depth': 31, 'min_samples_split': 643, 'min_samples_leaf': 72, 'max_features': 0.36261849860284495}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:08:48,825] Trial 67 finished with value: 335417500.0 and parameters: {'max_depth': 29, 'min_samples_split': 427, 'min_samples_leaf': 82, 'max_features': 0.37907998003744936}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:09:12,846] Trial 68 finished with value: 339817500.0 and parameters: {'max_depth': 27, 'min_samples_split': 547, 'min_samples_leaf': 57, 'max_features': 0.2135622299700777}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:09:46,780] Trial 69 finished with value: 340752500.0 and parameters: {'max_depth': 31, 'min_samples_split': 471, 'min_samples_leaf': 27, 'max_features': 0.28647100691211713}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:10:30,908] Trial 70 finished with value: 336710000.0 and parameters: {'max_depth': 29, 'min_samples_split': 328, 'min_samples_leaf': 91, 'max_features': 0.42875895514518747}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:10:58,878] Trial 71 finished with value: 337755000.0 and parameters: {'max_depth': 27, 'min_samples_split': 143, 'min_samples_leaf': 66, 'max_features': 0.2505447772088133}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:11:51,055] Trial 72 finished with value: 340862500.0 and parameters: {'max_depth': 28, 'min_samples_split': 48, 'min_samples_leaf': 54, 'max_features': 0.4707371705474321}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:12:23,502] Trial 73 finished with value: 337452500.0 and parameters: {'max_depth': 32, 'min_samples_split': 243, 'min_samples_leaf': 170, 'max_features': 0.35692420900322513}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:13:04,550] Trial 74 finished with value: 293260000.0 and parameters: {'max_depth': 31, 'min_samples_split': 1734, 'min_samples_leaf': 143, 'max_features': 0.3250027158504277}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:13:37,747] Trial 75 finished with value: 337232500.0 and parameters: {'max_depth': 25, 'min_samples_split': 116, 'min_samples_leaf': 188, 'max_features': 0.22403913698517422}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:14:02,917] Trial 76 finished with value: 331237500.0 and parameters: {'max_depth': 28, 'min_samples_split': 209, 'min_samples_leaf': 95, 'max_features': 0.1402238218233645}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:15:06,215] Trial 77 finished with value: 334702500.0 and parameters: {'max_depth': 30, 'min_samples_split': 344, 'min_samples_leaf': 82, 'max_features': 0.49147929660295}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:15:57,537] Trial 78 finished with value: 339845000.0 and parameters: {'max_depth': 29, 'min_samples_split': 517, 'min_samples_leaf': 62, 'max_features': 0.4547786918317298}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:21:11,810] Trial 79 finished with value: 339872500.0 and parameters: {'max_depth': 25, 'min_samples_split': 258, 'min_samples_leaf': 72, 'max_features': 0.3900039058933645}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:21:27,691] Trial 80 finished with value: 232292500.0 and parameters: {'max_depth': 2, 'min_samples_split': 422, 'min_samples_leaf': 155, 'max_features': 0.672152723884245}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:21:43,897] Trial 81 finished with value: 335142500.0 and parameters: {'max_depth': 23, 'min_samples_split': 284, 'min_samples_leaf': 47, 'max_features': 0.10521580931982123}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:22:07,834] Trial 82 finished with value: 338002500.0 and parameters: {'max_depth': 11, 'min_samples_split': 47, 'min_samples_leaf': 41, 'max_features': 0.20743615190175332}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:22:28,298] Trial 83 finished with value: 328432500.0 and parameters: {'max_depth': 27, 'min_samples_split': 162, 'min_samples_leaf': 133, 'max_features': 0.16820532298670812}. Best is trial 64 with value: 350377500.0.
[I 2026-09-07 18:22:51,538] Trial 84 finished with value: 331787500.0 and parameters: {'max_depth': 31, 'min_samples_split': 588, 'min_samples_leaf': 31, 'max_features': 0.18854932506371527}. Best is trial 64 with value: 350377500.0.

In [8]:
# PARA CARGAR SI YA OPTIMICE
storage_name = "sqlite:////Users/carof/Downloads/DENICOLAY/optimization_rf.db"
study_name = "exp_401_random-forest-opt"

# Cargar el estudio existente
study = optuna.load_study(study_name=study_name, storage=storage_name)

# Ver los mejores resultados
print(f"Mejor valor de ganancia: {study.best_value}")
print(f"Mejores hiperparámetros: {study.best_params}")

Mejor valor de ganancia: 350432500.0
Mejores hiperparámetros: {'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 50, 'max_features': 0.30786715539121634}

Exploramos como fue la búsqueda de parámetros

In [15]:
optuna.visualization.plot_optimization_history(study)

In [16]:
plot_param_importances(study)

In [17]:
plot_slice(study)

In [18]:
plot_contour(study)

In [19]:
plot_contour(study, params=["max_depth", "min_samples_split"])

Ajustamos el mejor modelo a todo el conjunto de datos

In [20]:
model_rf = RandomForestClassifier(
        n_estimators=100,
        **study.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf.fit(Xi, y)

RandomForestClassifier(max_depth=16, max_features=0.30786715539121634,
                       max_samples=0.7, min_samples_leaf=50,
                       min_samples_split=19, n_jobs=-1, oob_score=True,
                       random_state=688163)

Guardamos el modelo, para no tener que optimizar cada vez que lo queramos usar.

In [ ]:
filename = 'exp_206_random_forest_model_100.sav'
#pickle.dump(model_rf, open(filename, 'wb')) # descomentar para guardar

Y lo cargamos para utilizarlo

In [11]:
model_rf = pickle.load(open(filename, 'rb'))
model_rf

RandomForestClassifier(max_depth=16, max_features=0.30786715539121634,
                       max_samples=0.7, min_samples_leaf=50,
                       min_samples_split=19, n_jobs=-1, oob_score=True,
                       random_state=688163)

Ahora vamos medir su ganancia sobre el dataset de **Mayo**

In [16]:
y_pred_rf = model_rf.predict_proba(Xif) # Xif era el Imputado Futuro
ganancias_rf_100 = ganancia_prob(y_pred_rf, y_futuro)
print(f"Ganancia de modelo RF: {ganancias_rf_100}")

Ganancia de modelo RF: 256300000.0

Frente a los 208.010.000 de mi mejor árbol es algo sustancialmente mejor.

Igualmente usamos poquitos estimadores. Tan solo unos 100. Suficientes como para que la optimización no tarde una eternidad, pero es muy poco. Deberíamos sumar unos cuantos más.

### RF 1000

In [24]:
model_rf_1000 = RandomForestClassifier(
        n_estimators=1000,
        **study.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf_1000.fit(Xi, y) # descomentar para entrenar

RandomForestClassifier(max_depth=16, max_features=0.30786715539121634,
                       max_samples=0.7, min_samples_leaf=50,
                       min_samples_split=19, n_estimators=1000, n_jobs=-1,
                       oob_score=True, random_state=877804)

In [25]:
filename_rf_1000 = 'exp_206_random_forest_model_1000.sav'
pickle.dump(model_rf_1000, open(filename_rf_1000, 'wb')) # descomentar para guardar

In [26]:
filename_rf_1000 = 'exp_206_random_forest_model_1000.sav'
model_rf_1000 = pickle.load(open(filename_rf_1000, 'rb'))
model_rf_1000

RandomForestClassifier(max_depth=16, max_features=0.30786715539121634,
                       max_samples=0.7, min_samples_leaf=50,
                       min_samples_split=19, n_estimators=1000, n_jobs=-1,
                       oob_score=True, random_state=877804)

Veamos si sumar 10 veces más estimadores tuvo algún efecto

In [27]:
y_pred_rf = model_rf_1000.predict_proba(Xif)
ganancias_rf_1000 = ganancia_prob(y_pred_rf, y_futuro)
print(f"Ganancia de modelo RF 1000: {ganancias_rf_1000}")
print(f"Mejora respecto de modelo RF 1000: {ganancias_rf_100 - ganancias_rf_1000}")

Ganancia de modelo RF 1000: 258445000.0
Mejora respecto de modelo RF 1000: -2145000.0

Mejoró un poco! Cada peso vale.

### Feature importance

Por último evaluamos cuales son las variables más importantes del modelo. ¿Habrá influido la imputación?

In [28]:
importances = model_rf.feature_importances_

features = X.columns
feat_importances = pd.DataFrame({'feature': features, 'importance': importances})
feat_importances = feat_importances.sort_values('importance', ascending=False)

feat_importances.head(25)

                         feature  importance
107                 ctrx_quarter    0.140490
22                mcuentas_saldo    0.070104
18                  mcaja_ahorro    0.064515
11               mpasivos_margen    0.060336
33         mprestamos_personales    0.045252
8           mrentabilidad_annual    0.041054
16             mcuenta_corriente    0.038181
133                  Visa_status    0.028948
28         mtarjeta_visa_consumo    0.024659
7                  mrentabilidad    0.022076
10               mactivos_margen    0.020273
32         cprestamos_personales    0.018731
2                 active_quarter    0.017383
21      cdescubierto_preacordado    0.017145
6             cliente_antiguedad    0.016433
72     mcomisiones_mantenimiento    0.016404
12                    cproductos    0.015978
9                    mcomisiones    0.015741
5                   cliente_edad    0.015378
99              ccajas_consultas    0.014887
127             Master_fechaalta    0.014840
0              numero_de_cliente    0.014729
149               Visa_fechaalta    0.013726
74             mcomisiones_otras    0.013457
27   ctarjeta_visa_transacciones    0.013341

Vamos a hacer un par de experimentos, que pasa si sacamos la variable más importante?

In [ ]:
most_important_feature = feat_importances.iloc[0]['feature']

X_df = pd.DataFrame(Xi, columns=X.columns)
X_futuro_df = pd.DataFrame(Xif, columns=X_futuro.columns)

X_no_best_feature = X_df.drop(columns=[most_important_feature])
X_futuro_no_best_feature = X_futuro_df.drop(columns=[most_important_feature])

model_rf_no_best_feature = RandomForestClassifier(
    n_estimators=100,
    **study.best_params,
    max_samples=0.7,
    random_state=semillas[0],
    n_jobs=-1,
    oob_score=True
)

print(f"Entrenando modelo RF sin '{most_important_feature}'...")
model_rf_no_best_feature.fit(X_no_best_feature, y)

y_pred_rf_no_best_feature = model_rf_no_best_feature.predict_proba(X_futuro_no_best_feature)

ganancia_rf_no_best_feature = ganancia_prob(y_pred_rf_no_best_feature, y_futuro)

Entrenando modelo RF sin 'ctrx_quarter'...
Ganancia del modelo RF sin 'ctrx_quarter': 249425000.0
Ganancia del modelo RF original: 256300000.0

In [30]:
print(f"Ganancia de modelo sin '{most_important_feature}' {ganancia_rf_no_best_feature}: ")
print(f"Diferencia respecto de modelo RF 1000: {ganancias_rf_100 - ganancia_rf_no_best_feature}")

Ganancia de modelo sin 'ctrx_quarter' 249425000.0:
Diferencia respecto de modelo RF 1000: 6875000.0

¿Qué paso? ¿Se ha derrumbado las ganancias frente a la ausencia del pilar de los árboles?

Una prueba más, que pasa si sumamos variables que son ruido puro.

In [31]:
X_df_from_Xi = pd.DataFrame(Xi, columns=X.columns)

np.random.seed(semilla)

random_features_train = pd.DataFrame({
    f'random_feature_{i}': np.random.rand(len(X_df_from_Xi)) for i in range(1, 6)
})

X_with_random_features = pd.concat([X_df_from_Xi, random_features_train], axis=1)

model_rf_new_features = RandomForestClassifier(
    n_estimators=100,
    **study.best_params,
    max_samples=0.7,
    random_state=semillas[0],
    n_jobs=-1,
    oob_score=True
)

model_rf_new_features.fit(X_with_random_features, y)

importances_new_features = model_rf_new_features.feature_importances_

features_new_features = X_with_random_features.columns
feat_importances_new_features = pd.DataFrame({'feature': features_new_features, 'importance': importances_new_features})
feat_importances_new_features = feat_importances_new_features.sort_values('importance', ascending=False)

display(feat_importances_new_features.head(25))

                         feature  importance
107                 ctrx_quarter    0.112575
11               mpasivos_margen    0.069912
22                mcuentas_saldo    0.064221
18                  mcaja_ahorro    0.052660
33         mprestamos_personales    0.043998
8           mrentabilidad_annual    0.038392
16             mcuenta_corriente    0.037285
133                  Visa_status    0.031915
28         mtarjeta_visa_consumo    0.024686
7                  mrentabilidad    0.021234
2                 active_quarter    0.020446
32         cprestamos_personales    0.019113
10               mactivos_margen    0.018992
21      cdescubierto_preacordado    0.017534
12                    cproductos    0.017246
156             random_feature_3    0.015709
9                    mcomisiones    0.015304
72     mcomisiones_mantenimiento    0.014936
27   ctarjeta_visa_transacciones    0.014637
149               Visa_fechaalta    0.014482
99              ccajas_consultas    0.013828
5                   cliente_edad    0.013740
157             random_feature_4    0.013537
127             Master_fechaalta    0.012523
51                  cpayroll_trx    0.012430

Y una más, cual es el área bajo la curva en train?

In [ ]:
from sklearn.metrics import roc_auc_score

y_pred_rf_train = model_rf_1000.predict_proba(Xi)

ganancia_rf_train = ganancia_prob(y_pred_rf_train, y)
print(f"Ganancia en el conjunto de entrenamiento: {ganancia_rf_train}")
print(f"Ganancia en el conjunto de Mayo: {ganancias_rf_1000}")

y_train_numeric = (y == 'BAJA+2').astype(int) # dicotomizo
y_futuro_numeric = (y_futuro == 'BAJA+2').astype(int)

auc_train = roc_auc_score(y_train_numeric, y_pred_rf_train[:, 1])
print(f"Área bajo la curva (AUC) en el conjunto de entrenamiento: {auc_train}")

auc_mayo = roc_auc_score(y_futuro_numeric, y_pred_rf[:, 1])
print(f"Área bajo la curva (AUC) en el conjunto de Mayo: {auc_mayo}")

Ganancia en el conjunto de entrenamiento: 606512500.0
Ganancia en el conjunto de Mayo: 258445000.0
Área bajo la curva (AUC) en el conjunto de entrenamiento: 0.97180049967066
Área bajo la curva (AUC) en el conjunto de Mayo: 0.885930621841776

Cuanta diferencia entre conjuntos. Seguramente debemos descartar este algoritmo, ¿o no?

Pregunta:
* **¿Cómo sabe que un random forest es superior a otro?**
* **¿Cómo supera el random forest presentado?**

## Tarea:

* Mejore la parametrización del **rf**

### MEJORA OPTIMIZACION

Comparo su performance en test?
Como supero? creando nuevos features, optimizando

Cuando la consigna pide "mejorar la parametrización del Random Forest" tras haber corrido ya una optimización básica con Optuna, generalmente apunta a deficiencias en el diseño del espacio de búsqueda, en la estrategia de validación o en la configuración estructural del árbol.

**Revisar rangos y distribuciones de búsqueda en Optuna:**

Espacios lineales vs. logarítmicos: Hiperparámetros como min_samples_split (de 2 a 2000) o min_samples_leaf (de 1 a 200) suelen beneficiarse de distribuciones logarítmicas (trial.suggest_int('min_samples_split', 2, 2000, log=True)), ya que probar valores en escalas de magnitud (ej. 2, 10, 50, 200) explora mejor que una búsqueda uniforme.

Valores óptimos en los bordes: Si el mejor valor encontrado quedó pegado a uno de los extremos de tu rango (por ejemplo, max_features = 0.7 o max_depth = 32), el espacio de búsqueda estaba truncado y requiere ampliarse.

**Incorporar hiperparámetros faltantes:**

criterion: Evaluar "gini" frente a "entropy" / "log_loss".

max_samples: Dejaste fijo max_samples=0.7; optimizar este porcentaje de submuestreo (ej. entre 0.3 y 0.9) tiene un impacto directo en la varianza del ensamble.

class_weight: Si el problema tiene clases desbalanceadas, evaluar "balanced", "balanced_subsample" o ponderaciones personalizadas.

min_impurity_decrease: Controla la poda de divisiones que no aporten ganancia suficiente.

**Mejorar el esquema de validación y la función objetivo:**

Dependencia de oob_score: El cálculo OOB con 100 árboles puede tener alta varianza y sesgos si el dataset tiene estructura temporal o de grupos. Si se trata de series de tiempo o datos bancarios (común en problemas de optimización de ganancia), se suele requerir validación cruzada temporal o estratificada en lugar de OOB puro.

Número de árboles en la optimización: Optimizar con 100 árboles para luego entrenar con 1000 puede desplazar el punto óptimo de parámetros como max_features y min_samples_leaf, ya que un ensamble más grande tolera árboles más profundos y con mayor varianza individual.

**Aumentar el presupuesto de búsqueda:**

100 trials para un espacio continuo de 4 o más dimensiones puede ser insuficiente para que el muestreador bayesiano (TPE de Optuna) converja a un óptimo global robusto. Aumentar a 200–500 ensayos o cambiar el sampler (ej. TPESampler(multivariate=True)) mejora la exploración de correlaciones entre hiperparámetros.

Para usar validación cruzada en lugar de oob_score, utiliza StratifiedKFold (o KFold) para dividir los datos, entrena en los pliegues de entrenamiento y evalúa tu métrica ganancia_prob sobre las probabilidades predichas en cada conjunto de validación.

Desactiva oob_score=False (o quítalo) para ahorrar tiempo de cómputo innecesario:

In [34]:
# 5 folds estratificados
from sklearn.model_selection import StratifiedKFold
n_splits = 5
cv = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=semillas[0])

def objective(trial):
    max_depth = trial.suggest_int('max_depth', 2, 32)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 500, log=True)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 200, log=True)
    max_features = trial.suggest_float('max_features', 0.05, 0.7)
    max_samples = trial.suggest_float('max_samples', 0.3, 1.0)

    fold_scores = []

    for train_idx, val_idx in cv.split(Xi, y):
        X_train = Xi.iloc[train_idx] if hasattr(Xi, 'iloc') else Xi[train_idx]
        y_train = y.iloc[train_idx] if hasattr(y, 'iloc') else y[train_idx]
        X_val = Xi.iloc[val_idx] if hasattr(Xi, 'iloc') else Xi[val_idx]
        y_val = y.iloc[val_idx] if hasattr(y, 'iloc') else y[val_idx]

        model = RandomForestClassifier(
            n_estimators=200,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            max_features=max_features,
            max_samples=max_samples,
            random_state=semillas[0],
            n_jobs=-1,
            oob_score=False
        )

        model.fit(X_train, y_train)

        # Matriz completa de probabilidades (n_muestras, n_clases)
        y_val_probs = model.predict_proba(X_val)

        # Detectar la columna exacta de 'BAJA+2' dinámicamente
        target_class_idx = list(model.classes_).index("BAJA+2")

        # Se ajusta prop al tamaño del fold relativo al total
        fold_gain = ganancia_prob(
            y_hat=y_val_probs,
            y=y_val,
            prop=1 / n_splits,
            class_index=target_class_idx
        )
        fold_scores.append(fold_gain)

    return float(np.mean(fold_scores))

In [ ]:
# Ver los mejores resultados ANTERIORES
#print(f"Mejor valor de ganancia: {study.best_value}")
#print(f"Mejores hiperparámetros: {study.best_params}")

Mejor valor de ganancia: 350432500.0
Mejores hiperparámetros: {'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 50, 'max_features': 0.30786715539121634}

In [35]:
storage_name = "sqlite:////Users/carof/Downloads/DENICOLAY/optimization_rf.db"
study_name = "exp_401_random-forest-opt-vTarea"

study = optuna.create_study(
    direction="maximize",
    study_name=study_name,
    storage=storage_name,
    load_if_exists=True,
)

[I 2026-09-08 14:29:16,901] A new study created in RDB with name: exp_401_random-forest-opt-vTarea

In [ ]:
study.optimize(objective, n_trials=150)

[I 2026-09-08 14:37:19,192] Trial 0 finished with value: 311217500.0 and parameters: {'max_depth': 8, 'min_samples_split': 298, 'min_samples_leaf': 5, 'max_features': 0.5016464959948441, 'max_samples': 0.6720029296484965}. Best is trial 0 with value: 311217500.0.
[I 2026-09-08 14:51:22,055] Trial 1 finished with value: 297082500.0 and parameters: {'max_depth': 20, 'min_samples_split': 33, 'min_samples_leaf': 3, 'max_features': 0.3393453246702478, 'max_samples': 0.9978409801832846}. Best is trial 0 with value: 311217500.0.
[I 2026-09-08 15:03:52,354] Trial 2 finished with value: 339432500.0 and parameters: {'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 198, 'max_features': 0.6217546322766195, 'max_samples': 0.8226789400129564}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:08:00,413] Trial 3 finished with value: 324390000.0 and parameters: {'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 33, 'max_features': 0.3703942514393082, 'max_samples': 0.9689423041531944}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:12:28,315] Trial 4 finished with value: 273185000.0 and parameters: {'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.33861734945519245, 'max_samples': 0.4875156380844271}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:13:45,974] Trial 5 finished with value: 291280000.0 and parameters: {'max_depth': 6, 'min_samples_split': 466, 'min_samples_leaf': 1, 'max_features': 0.185778747815252, 'max_samples': 0.4395126695078808}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:20:56,748] Trial 6 finished with value: 302005000.0 and parameters: {'max_depth': 17, 'min_samples_split': 361, 'min_samples_leaf': 1, 'max_features': 0.30593515416958705, 'max_samples': 0.7209105183437619}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:22:54,773] Trial 7 finished with value: 333465000.0 and parameters: {'max_depth': 27, 'min_samples_split': 267, 'min_samples_leaf': 34, 'max_features': 0.15666912446805192, 'max_samples': 0.5861936334748535}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:24:38,641] Trial 8 finished with value: 280390000.0 and parameters: {'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.33777897695583575, 'max_samples': 0.647466121991529}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:38:17,951] Trial 9 finished with value: 279620000.0 and parameters: {'max_depth': 31, 'min_samples_split': 41, 'min_samples_leaf': 4, 'max_features': 0.6198926631542224, 'max_samples': 0.6539620953875097}. Best is trial 2 with value: 339432500.0.
[I 2026-09-08 15:50:32,991] Trial 10 finished with value: 346610000.0 and parameters: {'max_depth': 23, 'min_samples_split': 60, 'min_samples_leaf': 197, 'max_features': 0.6957753597213971, 'max_samples': 0.8617974816808877}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 16:02:19,978] Trial 11 finished with value: 341577500.0 and parameters: {'max_depth': 25, 'min_samples_split': 53, 'min_samples_leaf': 187, 'max_features': 0.6947339548777373, 'max_samples': 0.83802435881447}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 16:13:04,278] Trial 12 finished with value: 338937500.0 and parameters: {'max_depth': 24, 'min_samples_split': 69, 'min_samples_leaf': 199, 'max_features': 0.6663670316802136, 'max_samples': 0.8318986138908935}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 16:23:39,066] Trial 13 finished with value: 341990000.0 and parameters: {'max_depth': 23, 'min_samples_split': 92, 'min_samples_leaf': 69, 'max_features': 0.6995814547134396, 'max_samples': 0.8296561926058764}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 18:57:28,688] Trial 14 finished with value: 334152500.0 and parameters: {'max_depth': 20, 'min_samples_split': 127, 'min_samples_leaf': 58, 'max_features': 0.525387311157693, 'max_samples': 0.32048561937106285}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 19:05:13,987] Trial 15 finished with value: 343530000.0 and parameters: {'max_depth': 13, 'min_samples_split': 20, 'min_samples_leaf': 73, 'max_features': 0.5433805987984788, 'max_samples': 0.9065626562982728}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 19:20:28,245] Trial 16 finished with value: 341302500.0 and parameters: {'max_depth': 12, 'min_samples_split': 18, 'min_samples_leaf': 18, 'max_features': 0.5141010684689181, 'max_samples': 0.8980933649668341}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 19:29:19,096] Trial 17 finished with value: 343337500.0 and parameters: {'max_depth': 11, 'min_samples_split': 18, 'min_samples_leaf': 86, 'max_features': 0.5736846982830714, 'max_samples': 0.7562719690509249}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 19:54:23,706] Trial 18 finished with value: 335115000.0 and parameters: {'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 14, 'max_features': 0.4142663885659834, 'max_samples': 0.9115046544961317}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 20:13:16,452] Trial 19 finished with value: 340120000.0 and parameters: {'max_depth': 28, 'min_samples_split': 146, 'min_samples_leaf': 95, 'max_features': 0.46037699721626923, 'max_samples': 0.9223714510104034}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 20:13:59,296] Trial 20 finished with value: 325820000.0 and parameters: {'max_depth': 19, 'min_samples_split': 30, 'min_samples_leaf': 36, 'max_features': 0.05450983654676689, 'max_samples': 0.7656653187621549}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 20:57:20,151] Trial 21 finished with value: 340367500.0 and parameters: {'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 99, 'max_features': 0.5914022295911873, 'max_samples': 0.743836975572921}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 20:58:48,890] Trial 22 finished with value: 240185000.0 and parameters: {'max_depth': 2, 'min_samples_split': 21, 'min_samples_leaf': 122, 'max_features': 0.564722343306313, 'max_samples': 0.8803850409620763}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 21:05:43,358] Trial 23 finished with value: 338882500.0 and parameters: {'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 60, 'max_features': 0.5690793300003512, 'max_samples': 0.7614066765235857}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 21:12:30,015] Trial 24 finished with value: 332255000.0 and parameters: {'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 18, 'max_features': 0.643335523245563, 'max_samples': 0.579072038765238}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 21:19:35,761] Trial 25 finished with value: 345730000.0 and parameters: {'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 103, 'max_features': 0.45840800641900553, 'max_samples': 0.9479549102809038}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 21:25:51,049] Trial 26 finished with value: 345537500.0 and parameters: {'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 139, 'max_features': 0.4436712290481343, 'max_samples': 0.9376570080367728}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 21:29:41,548] Trial 27 finished with value: 342210000.0 and parameters: {'max_depth': 22, 'min_samples_split': 9, 'min_samples_leaf': 136, 'max_features': 0.26819881036905785, 'max_samples': 0.9582881063084051}. Best is trial 10 with value: 346610000.0.
[I 2026-09-08 21:37:09,989] Trial 28 finished with value: 351945000.0 and parameters: {'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 46, 'max_features': 0.43180116627854687, 'max_samples': 0.998551437284074}. Best is trial 28 with value: 351945000.0.
[I 2026-09-08 21:46:53,679] Trial 29 finished with value: 316745000.0 and parameters: {'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': 0.4753098095013749, 'max_samples': 0.9962542738503737}. Best is trial 28 with value: 351945000.0.
[I 2026-09-08 23:33:33,606] Trial 30 finished with value: 351862500.0 and parameters: {'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 43, 'max_features': 0.40782411273681335, 'max_samples': 0.8615238930325625}. Best is trial 28 with value: 351945000.0.
[I 2026-09-08 23:51:13,724] Trial 31 finished with value: 348425000.0 and parameters: {'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 42, 'max_features': 0.40477335339179166, 'max_samples': 0.8686586456766155}. Best is trial 28 with value: 351945000.0.
[I 2026-09-08 23:57:41,324] Trial 32 finished with value: 344410000.0 and parameters: {'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 44, 'max_features': 0.41214651368282207, 'max_samples': 0.8650030892179331}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 00:03:49,778] Trial 33 finished with value: 350487500.0 and parameters: {'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 24, 'max_features': 0.39766491153926725, 'max_samples': 0.7902257453273381}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 00:09:43,814] Trial 34 finished with value: 345207500.0 and parameters: {'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 24, 'max_features': 0.3853084000958003, 'max_samples': 0.7916336107273889}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 00:13:38,095] Trial 35 finished with value: 335555000.0 and parameters: {'max_depth': 29, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 0.27891953905170525, 'max_samples': 0.7012851603558983}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 00:19:23,773] Trial 36 finished with value: 342815000.0 and parameters: {'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 24, 'max_features': 0.37813606428762453, 'max_samples': 0.7960323595376249}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 00:23:13,783] Trial 37 finished with value: 344107500.0 and parameters: {'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 47, 'max_features': 0.23484944297381394, 'max_samples': 0.990179884811962}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 00:29:05,355] Trial 38 finished with value: 323125000.0 and parameters: {'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 0.4163312419538417, 'max_samples': 0.6887544427863176}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 00:34:20,327] Trial 39 finished with value: 348617500.0 and parameters: {'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 25, 'max_features': 0.34457796720586337, 'max_samples': 0.7938442874400903}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 01:37:43,689] Trial 40 finished with value: 347352500.0 and parameters: {'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 28, 'max_features': 0.3468097097378926, 'max_samples': 0.6107897044266477}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 01:42:32,671] Trial 41 finished with value: 348012500.0 and parameters: {'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 42, 'max_features': 0.3138703747672978, 'max_samples': 0.803101894430225}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 01:49:10,108] Trial 42 finished with value: 345207500.0 and parameters: {'max_depth': 24, 'min_samples_split': 6, 'min_samples_leaf': 17, 'max_features': 0.3706515888757086, 'max_samples': 0.8557948431225955}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 01:56:07,851] Trial 43 finished with value: 253742500.0 and parameters: {'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.4034065428703571, 'max_samples': 0.7178671559649048}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 02:04:13,316] Trial 44 finished with value: 322245000.0 and parameters: {'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 12, 'max_features': 0.47803657887764905, 'max_samples': 0.7934179027556694}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 02:10:05,661] Trial 45 finished with value: 348012500.0 and parameters: {'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 30, 'max_features': 0.3401606888556069, 'max_samples': 0.8816675202783602}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 02:18:15,232] Trial 46 finished with value: 300657500.0 and parameters: {'max_depth': 31, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 0.43019985066693894, 'max_samples': 0.8283984826762477}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 02:24:41,580] Trial 47 finished with value: 335252500.0 and parameters: {'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 25, 'max_features': 0.49592976885653356, 'max_samples': 0.6587269931545356}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 02:27:17,684] Trial 48 finished with value: 348205000.0 and parameters: {'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 50, 'max_features': 0.20845854505102543, 'max_samples': 0.7289409984725813}. Best is trial 28 with value: 351945000.0.
[I 2026-09-09 02:32:37,714] Trial 49 finished with value: 359810000.0 and parameters: {'max_depth': 32, 'min_samples_split': 7, 'min_samples_leaf': 34, 'max_features': 0.305501478340253, 'max_samples': 0.969850310007658}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 02:38:28,275] Trial 50 finished with value: 342980000.0 and parameters: {'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 19, 'max_features': 0.3177250302841792, 'max_samples': 0.9823491525338116}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 02:43:08,392] Trial 51 finished with value: 348645000.0 and parameters: {'max_depth': 32, 'min_samples_split': 5, 'min_samples_leaf': 38, 'max_features': 0.2827604695042582, 'max_samples': 0.9349803643874877}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 02:47:28,084] Trial 52 finished with value: 349140000.0 and parameters: {'max_depth': 32, 'min_samples_split': 12, 'min_samples_leaf': 66, 'max_features': 0.2772927515368146, 'max_samples': 0.9406644301154299}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 02:51:55,431] Trial 53 finished with value: 346692500.0 and parameters: {'max_depth': 32, 'min_samples_split': 13, 'min_samples_leaf': 73, 'max_features': 0.2833785381052253, 'max_samples': 0.9636686366101371}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 02:54:11,719] Trial 54 finished with value: 349690000.0 and parameters: {'max_depth': 32, 'min_samples_split': 11, 'min_samples_leaf': 59, 'max_features': 0.15888800226170202, 'max_samples': 0.9172986505451711}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 02:55:56,471] Trial 55 finished with value: 344630000.0 and parameters: {'max_depth': 30, 'min_samples_split': 25, 'min_samples_leaf': 60, 'max_features': 0.12656449554494528, 'max_samples': 0.9056476707488739}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 02:57:47,118] Trial 56 finished with value: 339020000.0 and parameters: {'max_depth': 31, 'min_samples_split': 10, 'min_samples_leaf': 51, 'max_features': 0.12586564487839172, 'max_samples': 0.9565603033782609}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:01:14,731] Trial 57 finished with value: 351835000.0 and parameters: {'max_depth': 29, 'min_samples_split': 11, 'min_samples_leaf': 79, 'max_features': 0.23821768284114742, 'max_samples': 0.9241195099257384}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:03:49,690] Trial 58 finished with value: 349717500.0 and parameters: {'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 33, 'max_features': 0.1712064977932055, 'max_samples': 0.890891299921572}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:07:17,636] Trial 59 finished with value: 345592500.0 and parameters: {'max_depth': 28, 'min_samples_split': 8, 'min_samples_leaf': 34, 'max_features': 0.23018727430453254, 'max_samples': 0.8466226312616763}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:10:11,799] Trial 60 finished with value: 352440000.0 and parameters: {'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 21, 'max_features': 0.18429642429679266, 'max_samples': 0.8954792377893029}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:13:22,488] Trial 61 finished with value: 339845000.0 and parameters: {'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 14, 'max_features': 0.1964849498796738, 'max_samples': 0.8828024388777905}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:15:54,449] Trial 62 finished with value: 343365000.0 and parameters: {'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 21, 'max_features': 0.16347326304785242, 'max_samples': 0.8961501637384288}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:20:03,483] Trial 63 finished with value: 352192500.0 and parameters: {'max_depth': 27, 'min_samples_split': 5, 'min_samples_leaf': 33, 'max_features': 0.24569466610032425, 'max_samples': 0.9736003340070041}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:23:39,515] Trial 64 finished with value: 346115000.0 and parameters: {'max_depth': 27, 'min_samples_split': 5, 'min_samples_leaf': 80, 'max_features': 0.23788918107364826, 'max_samples': 0.9737370366435804}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:27:58,997] Trial 65 finished with value: 346362500.0 and parameters: {'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 31, 'max_features': 0.2519830285219125, 'max_samples': 0.9945021157695635}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:31:34,119] Trial 66 finished with value: 335830000.0 and parameters: {'max_depth': 29, 'min_samples_split': 10, 'min_samples_leaf': 14, 'max_features': 0.2103856602250814, 'max_samples': 0.9291906396538949}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:32:21,930] Trial 67 finished with value: 312730000.0 and parameters: {'max_depth': 24, 'min_samples_split': 15, 'min_samples_leaf': 121, 'max_features': 0.12359394598987809, 'max_samples': 0.40564319115053327}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:37:02,183] Trial 68 finished with value: 351092500.0 and parameters: {'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 22, 'max_features': 0.30181758037251705, 'max_samples': 0.9693319164546108}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:41:44,555] Trial 69 finished with value: 342540000.0 and parameters: {'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 16, 'max_features': 0.29881531232943387, 'max_samples': 0.9694889960788204}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:43:39,008] Trial 70 finished with value: 318642500.0 and parameters: {'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 21, 'max_features': 0.2524883567234836, 'max_samples': 0.9184062374585594}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:47:32,669] Trial 71 finished with value: 340395000.0 and parameters: {'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 38, 'max_features': 0.35989927492678997, 'max_samples': 0.9537181398406925}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:52:18,930] Trial 72 finished with value: 352495000.0 and parameters: {'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 27, 'max_features': 0.3214712637151365, 'max_samples': 0.9953383121005006}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 03:57:18,261] Trial 73 finished with value: 357665000.0 and parameters: {'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 28, 'max_features': 0.31899758191735, 'max_samples': 0.9866803605952942}. Best is trial 49 with value: 359810000.0.
[I 2026-09-09 04:00:14,871] Trial 74 finished with value: 359122500.0 and parameters: {'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 28, 'max_features': 0.1872652466882126, 'max_samples': 0.9960600423126946}. Best is trial 49 with value: 359810000.0.

:

In [10]:
# PARA CARGAR SI YA OPTIMICE
storage_name = "sqlite:////Users/carof/Downloads/DENICOLAY/optimization_rf.db"
study_name = "exp_401_random-forest-opt-vTarea"

# Cargar el estudio existente
study = optuna.load_study(study_name=study_name, storage=storage_name)

# Ver los mejores resultados
print(f"Mejor valor de ganancia: {study.best_value}")
print(f"Mejores hiperparámetros: {study.best_params}")

Mejor valor de ganancia: 359810000.0
Mejores hiperparámetros: {'max_depth': 32, 'min_samples_split': 7, 'min_samples_leaf': 34, 'max_features': 0.305501478340253, 'max_samples': 0.969850310007658}

In [ ]:
# PARA CARGAR SI YA OPTIMICE # V Anterior para comparar
storage_name_anterior = "sqlite:////Users/carof/Downloads/DENICOLAY/optimization_rf.db"
study_name_anterior = "exp_401_random-forest-opt"

# Cargar el estudio existente
study_anterior = optuna.load_study(study_name=study_name_anterior, storage=storage_name_anterior)

# Ver los mejores resultados
print(f"Mejor valor de ganancia: {study_anterior.best_value}")
print(f"Mejores hiperparámetros: {study_anterior.best_params}")

Mejor valor de ganancia: 350432500.0
Mejores hiperparámetros: {'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 50, 'max_features': 0.30786715539121634}

In [11]:
study_anterior.best_value - study.best_value

-9377500.0

In [11]:
optuna.visualization.plot_optimization_history(study)

In [12]:
plot_param_importances(study)

In [13]:
plot_slice(study)

In [14]:
plot_contour(study)

In [13]:
model_rf_1000_vCaro = RandomForestClassifier(
        n_estimators=1000,
        **study.best_params,
        #max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf_1000_vCaro.fit(Xi, y) # descomentar para entrenar

RandomForestClassifier(max_depth=32, max_features=0.305501478340253,
                       max_samples=0.969850310007658, min_samples_leaf=34,
                       min_samples_split=7, n_estimators=1000, n_jobs=-1,
                       oob_score=True, random_state=550646)

In [14]:
filename_rf_1000_vCaro = 'exp_206_random_forest_model_1000_vCaro.sav'
pickle.dump(model_rf_1000_vCaro, open(filename_rf_1000_vCaro, 'wb')) # descomentar para guardar

In [15]:
y_pred_rf_vCaro = model_rf_1000_vCaro.predict_proba(Xif)
ganancias_rf_1000_vCaro = ganancia_prob(y_pred_rf_vCaro, y_futuro)

In [16]:
print(f"Ganancia de modelo RF 1000: {ganancias_rf_1000_vCaro}")

Ganancia de modelo RF 1000: 255915000.0

Ganancia de modelo RF 1000: 258445000.0
Mejora respecto de modelo RF 1000: -2145000.0

In [18]:
258445000 - 255915000

2530000

### RETRAIN Y OPTIMIZACION DESP DE FE

In [2]:
dataset_path = "/Users/carof/Downloads/DENICOLAY/"
parquet_file = f"{dataset_path}/competencia_01_fe.parquet"

data = pd.read_parquet(parquet_file)

# Verificación rápida
print(data.shape)
data.head()

(983061, 233)

,numero_de_cliente,foto_mes,active_quarter,cliente_vip,internet,cliente_edad,cliente_antiguedad,mrentabilidad,mrentabilidad_annual,mcomisiones,...,ctrx_quarter_ratio3,cconsumos_tc_ratio1,cconsumos_tc_ratio3,ctrx_quarter_ratio_avg3m,mcuentas_saldo_ratio_avg3m,ctrx_distancia_pico6m,mcuentas_saldo_distancia_pico6m,flag_cesacion_payroll,flag_vaciado_cuentas,flag_abandono_consumo_tc
0,12160484,202103,1,0,0,60,55,8101.55,3162.23,13399.50,...,NaN,NaN,NaN,1.0000,1.0000,1.0000,1.0000,0,0,0
1,12160484,202104,1,0,0,60,56,-3703.99,-1363.50,2091.38,...,NaN,0.8571,NaN,0.8889,-3.7943,0.8000,-0.6548,0,1,0
2,12160484,202105,1,0,0,60,57,-2660.01,-4707.72,2152.44,...,NaN,0.8333,NaN,0.7643,-1.7797,0.6154,-0.1285,0,0,0
3,12160484,202106,1,0,0,60,58,-1876.81,-6742.99,2438.26,...,0.5152,1.1000,0.7857,0.7920,-60.1410,0.5077,0.7461,0,0,0
4,12160484,202107,1,0,0,60,59,-2941.46,-8218.09,2929.35,...,0.5472,0.9091,0.8333,0.8317,-1.0464,0.4308,-0.1597,0,1,0

In [19]:
data.describe(include="all")

,numero_de_cliente,foto_mes,active_quarter,cliente_vip,internet,cliente_edad,cliente_antiguedad,mrentabilidad,mrentabilidad_annual,mcomisiones,...,ctrx_quarter_ratio3,cconsumos_tc_ratio1,cconsumos_tc_ratio3,ctrx_quarter_ratio_avg3m,mcuentas_saldo_ratio_avg3m,ctrx_distancia_pico6m,mcuentas_saldo_distancia_pico6m,flag_cesacion_payroll,flag_vaciado_cuentas,flag_abandono_consumo_tc
count,9.830610e+05,983061.000000,983061.000000,983061.000000,983061.000000,983061.000000,983061.000000,983061.000000,9.830610e+05,983061.000000,...,480791.000000,813334.000000,480791.000000,975224.000000,978024.000000,976060.000000,9.770770e+05,983061.000000,983061.000000,983061.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,3.779833e+07,202105.506242,0.986954,0.003166,0.049117,46.884686,134.912766,2445.401757,2.484136e+04,1614.815041,...,1.107446,1.079329,1.194301,1.009897,2.172180,0.925760,-1.161873e+01,0.011059,0.047555,0.006817
std,1.586785e+07,1.707532,0.113472,0.056175,0.271282,12.987574,86.282920,8267.171556,6.822922e+04,3122.676446,...,1.030150,0.770395,1.135972,0.135415,794.057705,0.135264,3.548650e+03,0.104580,0.212822,0.082286
min,1.215985e+07,202103.000000,0.000000,0.000000,0.000000,18.000000,1.000000,-271488.390000,-9.380887e+05,-52407.900000,...,0.004600,0.004400,0.004400,0.000000,-43396.540500,0.000000,-2.006054e+06,0.000000,0.000000,0.000000
25%,2.549570e+07,202104.000000,1.000000,0.000000,0.000000,37.000000,63.000000,71.110000,1.884690e+03,366.730000,...,0.895300,0.900000,0.885700,0.971200,0.804600,0.898300,4.780000e-01,0.000000,0.000000,0.000000
50%,3.596115e+07,202106.000000,1.000000,0.000000,0.000000,45.000000,128.000000,1416.530000,1.334347e+04,981.750000,...,1.027800,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000,0.000000,0.000000
75%,4.905971e+07,202107.000000,1.000000,0.000000,0.000000,56.000000,190.000000,3304.210000,3.206790e+04,2181.850000,...,1.184000,1.142900,1.272700,1.050500,1.205000,1.000000,1.000000e+00,0.000000,0.000000,0.000000
max,7.825496e+07,202108.000000,1.000000,1.000000,4.000000,101.000000,380.000000,784129.030000,7.023011e+06,513155.480000,...,115.000000,188.000000,136.000000,3.000000,741129.750000,1.000000,4.990700e+05,1.000000,1.000000,1.000000

In [21]:
pd.set_option("display.max_rows", None)
data.isnull().mean() * 100

numero_de_cliente                         0.000000
foto_mes                                  0.000000
active_quarter                            0.000000
cliente_vip                               0.000000
internet                                  0.000000
cliente_edad                              0.000000
cliente_antiguedad                        0.000000
mrentabilidad                             0.000000
mrentabilidad_annual                      0.000000
mcomisiones                               0.000000
mactivos_margen                           0.000000
mpasivos_margen                           0.000000
cproductos                                0.000000
tcuentas                                  0.000000
ccuenta_corriente                         0.000000
mcuenta_corriente_adicional               0.000000
mcuenta_corriente                         0.000000
ccaja_ahorro                              0.000000
mcaja_ahorro                              0.000000
mcaja_ahorro_adicional                    0.000000
mcaja_ahorro_dolares                      0.000000
cdescubierto_preacordado                  0.000000
mcuentas_saldo                            0.000000
ctarjeta_debito                           0.000000
ctarjeta_debito_transacciones             0.000000
mautoservicio                             0.000000
ctarjeta_visa                             0.000000
ctarjeta_visa_transacciones               0.000000
mtarjeta_visa_consumo                     0.000000
ctarjeta_master                           0.000000
ctarjeta_master_transacciones             0.000000
mtarjeta_master_consumo                   0.000000
cprestamos_personales                     0.000000
mprestamos_personales                     0.000000
cprestamos_prendarios                     0.000000
mprestamos_prendarios                     0.000000
cprestamos_hipotecarios                   0.000000
mprestamos_hipotecarios                   0.000000
cplazo_fijo                               0.000000
mplazo_fijo_dolares                       0.000000
mplazo_fijo_pesos                         0.000000
cinversion1                               0.000000
minversion1_pesos                         0.000000
minversion1_dolares                       0.000000
cinversion2                               0.000000
minversion2                               0.000000
cseguro_vida                              0.000000
cseguro_auto                              0.000000
cseguro_vivienda                          0.000000
cseguro_accidentes_personales             0.000000
ccaja_seguridad                           0.000000
cpayroll_trx                              0.000000
mpayroll                                  0.000000
mpayroll2                                 0.000000
cpayroll2_trx                             0.000000
ccuenta_debitos_automaticos               0.000000
mcuenta_debitos_automaticos               0.000000
ctarjeta_visa_debitos_automaticos         0.000000
mttarjeta_visa_debitos_automaticos        0.000000
ctarjeta_master_debitos_automaticos       0.000000
mttarjeta_master_debitos_automaticos      0.000000
cpagodeservicios                          0.000000
mpagodeservicios                          0.000000
cpagomiscuentas                           0.000000
mpagomiscuentas                           0.000000
ccajeros_propios_descuentos               0.000000
mcajeros_propios_descuentos               0.000000
ctarjeta_visa_descuentos                  0.000000
mtarjeta_visa_descuentos                  2.105058
ctarjeta_master_descuentos                0.000000
mtarjeta_master_descuentos                2.968076
ccomisiones_mantenimiento                 0.000000
mcomisiones_mantenimiento                 0.000000
ccomisiones_otras                         0.000000
mcomisiones_otras                         0.000000
cforex                                    0.000000
cforex_buy                                0.000000
mforex_buy                                0.000000
cforex_sell                               0.000000
mforex_sell                               0.000000
ctransferencias_recibidas                 0.000000
mtransferencias_recibidas                 0.000000
ctransferencias_emitidas                  0.000000
mtransferencias_emitidas                  0.000000
cextraccion_autoservicio                  0.000000
mextraccion_autoservicio                  0.000000
ccheques_depositados                      0.000000
mcheques_depositados                      0.000000
ccheques_emitidos                         0.000000
mcheques_emitidos                         0.000000
ccheques_depositados_rechazados           0.000000
mcheques_depositados_rechazados           0.000000
ccheques_emitidos_rechazados              0.000000
mcheques_emitidos_rechazados              0.000000
tcallcenter                               0.000000
ccallcenter_transacciones                 0.000000
thomebanking                              0.000000
chomebanking_transacciones                0.000000
ccajas_transacciones                      0.000000
ccajas_consultas                          0.000000
ccajas_depositos                          0.000000
ccajas_extracciones                       0.000000
ccajas_otras                              0.000000
catm_trx                                  0.000000
matm                                      0.000000
catm_trx_other                            0.000000
matm_other                                0.000000
ctrx_quarter                              0.000000
tmobile_app                               0.000000
cmobile_app_trx                           0.000000
Master_delinquency                       10.136095
Master_status                            10.136095
Master_mfinanciacion_limite              10.136095
Master_Fvencimiento                      10.136095
Master_Finiciomora                       99.509593
Master_msaldototal                       10.136095
Master_msaldopesos                       10.136095
Master_msaldodolares                     10.136095
Master_mconsumospesos                    58.945477
Master_mconsumosdolares                  58.945477
Master_mlimitecompra                     10.136095
Master_madelantopesos                    58.945477
Master_madelantodolares                  58.945477
Master_fultimo_cierre                    10.185228
Master_mpagado                           10.136095
Master_mpagospesos                       58.945477
Master_mpagosdolares                     58.945477
Master_fechaalta                         10.136095
Master_mconsumototal                     58.945477
Master_cconsumos                         58.945477
Master_cadelantosefectivo                58.945477
Master_mpagominimo                       10.136095
Visa_delinquency                          4.799906
Visa_status                               4.799906
Visa_mfinanciacion_limite                 4.799906
Visa_Fvencimiento                         4.799906
Visa_Finiciomora                         98.644845
Visa_msaldototal                          4.799906
Visa_msaldopesos                          4.799906
Visa_msaldodolares                        4.799906
Visa_mconsumospesos                      12.996142
Visa_mconsumosdolares                    12.996142
Visa_mlimitecompra                        4.799906
Visa_madelantopesos                      12.996142
Visa_madelantodolares                    12.996142
Visa_fultimo_cierre                       4.835509
Visa_mpagado                              4.799906
Visa_mpagospesos                         12.996142
Visa_mpagosdolares                       12.996142
Visa_fechaalta                            4.799906
Visa_mconsumototal                       12.996142
Visa_cconsumos                           12.996142
Visa_cadelantosefectivo                  12.996142
Visa_mpagominimo                          4.799906
clase_ternaria                           33.354187
mconsumototal_tc                          0.000000
cconsumos_total_tc                        0.000000
msaldototal_tc                            0.000000
mlimitecompra_total                       0.000000
mpagominimo_total                         0.000000
mpagado_total                             0.000000
saldo_liquido_total                       0.000000
deuda_prestamos_total                     0.000000
trx_digitales                             0.000000
trx_fisicas                               0.000000
ratio_utilizacion_limite                  3.994360
ratio_pago_vs_saldo                      11.649328
ratio_pago_minimo                        15.315530
ratio_liquidez_vs_deuda                  76.934900
ratio_canal_digital                       4.198620
ticket_promedio_visa                     14.630933
ticket_promedio_master                   62.316377
ticket_promedio_debito                   28.995861
antiguedad_meses_visa                   100.000000
antiguedad_meses_master                 100.000000
ctrx_quarter_lag1                        17.265154
ctrx_quarter_lag2                        34.283630
ctrx_quarter_lag3                        51.092455
ctrx_quarter_lag6                       100.000000
cproductos_lag1                          17.265154
cproductos_lag2                          34.283630
cproductos_lag3                          51.092455
chb_trx_lag1                             17.265154
cmobile_trx_lag1                         17.265154
cconsumos_tc_lag1                        17.265154
cconsumos_tc_lag3                        51.092455
mcuentas_saldo_lag1                      17.265154
mcuentas_saldo_lag2                      34.283630
mcuentas_saldo_lag3                      51.092455
mcuentas_saldo_lag6                     100.000000
mpayroll_lag1                            17.265154
mpayroll_lag2                            34.283630
mrentabilidad_lag1                       17.265154
mrentabilidad_lag3                       51.092455
mconsumototal_tc_lag1                    17.265154
mconsumototal_tc_lag3                    51.092455
ctrx_quarter_avg3m                        0.000000
ctrx_quarter_std3m                       17.265154
mcuentas_saldo_avg3m                      0.000000
mcuentas_saldo_std3m                     17.265154
mrentabilidad_avg3m                       0.000000
mconsumototal_tc_avg3m                    0.000000
ctrx_quarter_avg6m                        0.000000
ctrx_quarter_max6m                        0.000000
ctrx_quarter_min6m                        0.000000
mcuentas_saldo_avg6m                      0.000000
mcuentas_saldo_max6m                      0.000000
mcuentas_saldo_min6m                      0.000000
ctrx_quarter_delta1                      17.265154
ctrx_quarter_delta2                      34.283630
ctrx_quarter_delta3                      51.092455
ctrx_quarter_delta6                     100.000000
cproductos_delta1                        17.265154
cproductos_delta3                        51.092455
mcuentas_saldo_delta1                    17.265154
mcuentas_saldo_delta2                    34.283630
mcuentas_saldo_delta3                    51.092455
mcuentas_saldo_delta6                   100.000000
mrentabilidad_delta1                     17.265154
mrentabilidad_delta3                     51.092455
mconsumototal_tc_delta1                  17.265154
mconsumototal_tc_delta3                  51.092455
ctrx_quarter_ratio1                      17.265154
ctrx_quarter_ratio3                      51.092455
cconsumos_tc_ratio1                      17.265154
cconsumos_tc_ratio3                      51.092455
ctrx_quarter_ratio_avg3m                  0.797204
mcuentas_saldo_ratio_avg3m                0.512379
ctrx_distancia_pico6m                     0.712163
mcuentas_saldo_distancia_pico6m           0.608711
flag_cesacion_payroll                     0.000000
flag_vaciado_cuentas                      0.000000
flag_abandono_consumo_tc                  0.000000
dtype: float64

Claramente los lag6 son inutiles

Hacemos algo mas de preprocessing

In [3]:
# Dummy para Master: 1 si tiene dato, 0 si es NaN
data["dummy_Master_mora"] = data["Master_Finiciomora"].notna().astype(int)

# Dummy para Visa: 1 si tiene dato, 0 si es NaN
data["dummy_Visa_mora"] = data["Visa_Finiciomora"].notna().astype(int)

In [4]:
# Cantidad y porcentaje de nulos en el DataFrame (o en tu train set)
nulos_por_col = data.isnull().mean() * 100

# Filtrar únicamente las columnas que tienen 100% de valores nulos
cols_totalmente_nulas = nulos_por_col[nulos_por_col == 100.0].index.tolist()
print(f"Total de columnas 100% nulas: {len(cols_totalmente_nulas)}")
print(cols_totalmente_nulas)

# Eliminar todas las columnas que tengan 100% de nulos de forma automática
cols_a_borrar = data.columns[data.isnull().all()].tolist()
data = data.drop(columns=cols_a_borrar)

Total de columnas 100% nulas: 6
['antiguedad_meses_visa', 'antiguedad_meses_master', 'ctrx_quarter_lag6', 'mcuentas_saldo_lag6', 'ctrx_quarter_delta6', 'mcuentas_saldo_delta6']

In [24]:
data.shape

(983061, 229)

In [5]:
mes_train = 202103
mes_test = 202105

# agregue sus semillas
semilla = 42
semillas = np.random.choice(1000000, size=50, replace=False).tolist()

In [6]:
X = data[data['foto_mes'] == mes_train]
y = X['clase_ternaria']
X = X.drop(columns=['clase_ternaria'])

In [7]:
X_futuro = data[data['foto_mes'] == mes_test]
y_futuro = X_futuro['clase_ternaria']
X_futuro = X_futuro.drop(columns=['clase_ternaria'])

In [ ]:
#imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
#Xi = imp_median.fit_transform(X)
#Xif = imp_median.fit_transform(X_futuro)
# No voy a imputar, tengo muchos nulos y a un compa le dio mejor dejandolo asi como esta, RF ahora los maneja

In [8]:
ganancia_acierto = 1_072_500
costo_estimulo = 27_500

def ganancia_prob(y_hat, y, prop=1, class_index=1, threshold=0.025):
  @np.vectorize
  def ganancia_row(predicted, actual, threshold=0.025):
    return  (predicted >= threshold) * (ganancia_acierto if actual == "BAJA+2" else -costo_estimulo)

  return ganancia_row(y_hat[:,class_index], y).sum() / prop

In [9]:
# 5 folds estratificados #Xi
from sklearn.model_selection import StratifiedKFold
n_splits = 5
cv = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=semillas[0])

def objective(trial):
    max_depth = trial.suggest_int('max_depth', 2, 25)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 400, log=True)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 200, log=True)
    max_features = trial.suggest_float('max_features', 0.05, 0.7)
    max_samples = trial.suggest_float('max_samples', 0.4, 1.0)

    fold_scores = []

    for train_idx, val_idx in cv.split(X, y):
        X_train = X.iloc[train_idx] if hasattr(X, 'iloc') else X[train_idx]
        y_train = y.iloc[train_idx] if hasattr(y, 'iloc') else y[train_idx]
        X_val = X.iloc[val_idx] if hasattr(X, 'iloc') else X[val_idx]
        y_val = y.iloc[val_idx] if hasattr(y, 'iloc') else y[val_idx]

        model = RandomForestClassifier(
            n_estimators=200,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            max_features=max_features,
            max_samples=max_samples,
            random_state=semillas[0],
            n_jobs=-1,
            oob_score=False
        )

        model.fit(X_train, y_train)

        # Matriz completa de probabilidades (n_muestras, n_clases)
        y_val_probs = model.predict_proba(X_val)

        # Detectar la columna exacta de 'BAJA+2' dinámicamente
        target_class_idx = list(model.classes_).index("BAJA+2")

        # Se ajusta prop al tamaño del fold relativo al total
        fold_gain = ganancia_prob(
            y_hat=y_val_probs,
            y=y_val,
            prop=1 / n_splits,
            class_index=target_class_idx
        )
        fold_scores.append(fold_gain)

    return float(np.mean(fold_scores))

In [30]:
storage_name = "sqlite:////Users/carof/Downloads/DENICOLAY/optimization_rf.db"
study_name = "exp_401_random-forest-opt-vFE13sept"

study = optuna.create_study(
    direction="maximize",
    study_name=study_name,
    storage=storage_name,
    load_if_exists=True,
)

[I 2026-09-13 14:17:41,182] Using an existing study with name 'exp_401_random-forest-opt-vFE13sept' instead of creating a new one.

In [ ]:
study.optimize(objective, n_trials=100)

[I 2026-09-13 14:28:11,527] Trial 1 finished with value: 338662500.0 and parameters: {'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 51, 'max_features': 0.6469832642813235, 'max_samples': 0.570706558563491}. Best is trial 1 with value: 338662500.0.
[I 2026-09-13 14:31:37,302] Trial 2 finished with value: 323675000.0 and parameters: {'max_depth': 6, 'min_samples_split': 63, 'min_samples_leaf': 76, 'max_features': 0.31541762933464373, 'max_samples': 0.7465247626783105}. Best is trial 1 with value: 338662500.0.
[I 2026-09-13 14:37:14,064] Trial 3 finished with value: 310447500.0 and parameters: {'max_depth': 9, 'min_samples_split': 53, 'min_samples_leaf': 6, 'max_features': 0.5241367695316642, 'max_samples': 0.4259144956071651}. Best is trial 1 with value: 338662500.0.
[I 2026-09-13 14:38:22,380] Trial 4 finished with value: 305745000.0 and parameters: {'max_depth': 6, 'min_samples_split': 212, 'min_samples_leaf': 10, 'max_features': 0.07711944721252117, 'max_samples': 0.9412866524834206}. Best is trial 1 with value: 338662500.0.
[I 2026-09-13 15:19:33,444] Trial 5 finished with value: 315260000.0 and parameters: {'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 0.690322554941336, 'max_samples': 0.9631335486051402}. Best is trial 1 with value: 338662500.0.
[I 2026-09-13 15:29:23,634] Trial 6 finished with value: 339102500.0 and parameters: {'max_depth': 11, 'min_samples_split': 202, 'min_samples_leaf': 96, 'max_features': 0.46674698103932766, 'max_samples': 0.6859399567915537}. Best is trial 6 with value: 339102500.0.
[I 2026-09-13 15:33:12,966] Trial 7 finished with value: 328817500.0 and parameters: {'max_depth': 6, 'min_samples_split': 185, 'min_samples_leaf': 53, 'max_features': 0.2709057265632426, 'max_samples': 0.9974730800563938}. Best is trial 6 with value: 339102500.0.
[I 2026-09-13 15:37:07,897] Trial 8 finished with value: 271067500.0 and parameters: {'max_depth': 4, 'min_samples_split': 187, 'min_samples_leaf': 2, 'max_features': 0.4960794740231646, 'max_samples': 0.8586571894650386}. Best is trial 6 with value: 339102500.0.
[I 2026-09-13 15:43:40,530] Trial 9 finished with value: 335005000.0 and parameters: {'max_depth': 19, 'min_samples_split': 45, 'min_samples_leaf': 173, 'max_features': 0.3480369875874897, 'max_samples': 0.5405716370255707}. Best is trial 6 with value: 339102500.0.
[I 2026-09-13 16:20:50,452] Trial 10 finished with value: 261277500.0 and parameters: {'max_depth': 23, 'min_samples_split': 24, 'min_samples_leaf': 2, 'max_features': 0.6316131739396585, 'max_samples': 0.9719747125580293}. Best is trial 6 with value: 339102500.0.
[I 2026-09-13 16:23:08,504] Trial 11 finished with value: 325352500.0 and parameters: {'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 13, 'max_features': 0.07074596852023729, 'max_samples': 0.6877293984887731}. Best is trial 6 with value: 339102500.0.
[I 2026-09-13 16:35:44,156] Trial 12 finished with value: 333960000.0 and parameters: {'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 34, 'max_features': 0.520449713787898, 'max_samples': 0.5953619168258327}. Best is trial 6 with value: 339102500.0.
[I 2026-09-13 16:44:34,801] Trial 13 finished with value: 341385000.0 and parameters: {'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 181, 'max_features': 0.4160568004456971, 'max_samples': 0.621310916317505}. Best is trial 13 with value: 341385000.0.
[I 2026-09-13 16:55:38,827] Trial 14 finished with value: 340395000.0 and parameters: {'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 161, 'max_features': 0.42566174293971976, 'max_samples': 0.7274312501970959}. Best is trial 13 with value: 341385000.0.
[I 2026-09-13 17:07:25,524] Trial 15 finished with value: 342870000.0 and parameters: {'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 183, 'max_features': 0.4010209792728627, 'max_samples': 0.7970611117281172}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 20:45:05,818] Trial 16 finished with value: 338662500.0 and parameters: {'max_depth': 22, 'min_samples_split': 4, 'min_samples_leaf': 26, 'max_features': 0.20876241601036463, 'max_samples': 0.8187518256412639}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 20:47:44,525] Trial 17 finished with value: 322602500.0 and parameters: {'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 200, 'max_features': 0.36709681766184665, 'max_samples': 0.43439344667742835}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 20:50:57,982] Trial 18 finished with value: 338910000.0 and parameters: {'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 104, 'max_features': 0.22625484291700457, 'max_samples': 0.8366210197045282}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 21:09:46,443] Trial 19 finished with value: 327552500.0 and parameters: {'max_depth': 9, 'min_samples_split': 15, 'min_samples_leaf': 30, 'max_features': 0.41105534152316564, 'max_samples': 0.6202991202659165}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 21:11:37,774] Trial 20 finished with value: 298567500.0 and parameters: {'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.15846751038170015, 'max_samples': 0.4958345372431683}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 21:17:36,640] Trial 21 finished with value: 337617500.0 and parameters: {'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 104, 'max_features': 0.4103892698293557, 'max_samples': 0.7823267830603213}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 21:22:44,965] Trial 22 finished with value: 340642500.0 and parameters: {'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 167, 'max_features': 0.43689112288925785, 'max_samples': 0.6985791571922618}. Best is trial 15 with value: 342870000.0.
[I 2026-09-13 21:30:19,363] Trial 23 finished with value: 348370000.0 and parameters: {'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 196, 'max_features': 0.5570498219838055, 'max_samples': 0.8927344719942316}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 21:40:45,416] Trial 24 finished with value: 341577500.0 and parameters: {'max_depth': 25, 'min_samples_split': 28, 'min_samples_leaf': 62, 'max_features': 0.5948452219164974, 'max_samples': 0.9013026846935511}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 21:50:43,598] Trial 25 finished with value: 339322500.0 and parameters: {'max_depth': 25, 'min_samples_split': 30, 'min_samples_leaf': 58, 'max_features': 0.5752133742672523, 'max_samples': 0.9017884841599086}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 22:02:00,648] Trial 26 finished with value: 320127500.0 and parameters: {'max_depth': 22, 'min_samples_split': 81, 'min_samples_leaf': 18, 'max_features': 0.5751593964297275, 'max_samples': 0.8929666348495917}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 22:11:00,319] Trial 27 finished with value: 340890000.0 and parameters: {'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 102, 'max_features': 0.5667999833138974, 'max_samples': 0.9101089822019955}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 22:17:07,924] Trial 28 finished with value: 342595000.0 and parameters: {'max_depth': 9, 'min_samples_split': 400, 'min_samples_leaf': 39, 'max_features': 0.6406721654319945, 'max_samples': 0.799286123096797}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 22:23:57,773] Trial 29 finished with value: 335775000.0 and parameters: {'max_depth': 9, 'min_samples_split': 118, 'min_samples_leaf': 37, 'max_features': 0.6962559276813396, 'max_samples': 0.7907476833754882}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 22:25:36,842] Trial 30 finished with value: 229405000.0 and parameters: {'max_depth': 2, 'min_samples_split': 124, 'min_samples_leaf': 20, 'max_features': 0.6557056217313401, 'max_samples': 0.8585822597229454}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 23:00:55,259] Trial 31 finished with value: 327140000.0 and parameters: {'max_depth': 11, 'min_samples_split': 398, 'min_samples_leaf': 8, 'max_features': 0.6250982178007163, 'max_samples': 0.773845541862453}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 23:10:58,890] Trial 32 finished with value: 329422500.0 and parameters: {'max_depth': 18, 'min_samples_split': 400, 'min_samples_leaf': 66, 'max_features': 0.619189056855477, 'max_samples': 0.8759725679493042}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 23:19:13,636] Trial 33 finished with value: 345620000.0 and parameters: {'max_depth': 15, 'min_samples_split': 30, 'min_samples_leaf': 47, 'max_features': 0.5505748144590037, 'max_samples': 0.8293719005239002}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 23:26:26,374] Trial 34 finished with value: 338277500.0 and parameters: {'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 117, 'max_features': 0.5395959101654745, 'max_samples': 0.8159257809815784}. Best is trial 23 with value: 348370000.0.
[I 2026-09-13 23:32:50,795] Trial 35 finished with value: 348645000.0 and parameters: {'max_depth': 14, 'min_samples_split': 40, 'min_samples_leaf': 43, 'max_features': 0.4804036182242227, 'max_samples': 0.7492518758596718}. Best is trial 35 with value: 348645000.0.
[I 2026-09-13 23:38:48,625] Trial 36 finished with value: 341467500.0 and parameters: {'max_depth': 14, 'min_samples_split': 43, 'min_samples_leaf': 83, 'max_features': 0.4796831564048086, 'max_samples': 0.7349885711622788}. Best is trial 35 with value: 348645000.0.
[I 2026-09-13 23:43:10,711] Trial 37 finished with value: 341467500.0 and parameters: {'max_depth': 12, 'min_samples_split': 77, 'min_samples_leaf': 45, 'max_features': 0.3652610078848524, 'max_samples': 0.7536901938506615}. Best is trial 35 with value: 348645000.0.
[I 2026-09-13 23:50:50,705] Trial 38 finished with value: 325105000.0 and parameters: {'max_depth': 17, 'min_samples_split': 17, 'min_samples_leaf': 17, 'max_features': 0.534675246624395, 'max_samples': 0.6595936343900116}. Best is trial 35 with value: 348645000.0.
[I 2026-09-13 23:55:53,188] Trial 39 finished with value: 303242500.0 and parameters: {'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 0.302438789123763, 'max_samples': 0.9367609085704438}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 00:01:20,156] Trial 40 finished with value: 338112500.0 and parameters: {'max_depth': 11, 'min_samples_split': 39, 'min_samples_leaf': 130, 'max_features': 0.4753503426092847, 'max_samples': 0.8547860360014025}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 00:08:58,922] Trial 41 finished with value: 337177500.0 and parameters: {'max_depth': 15, 'min_samples_split': 63, 'min_samples_leaf': 83, 'max_features': 0.5032536817680787, 'max_samples': 0.9368447680044968}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 00:15:57,504] Trial 42 finished with value: 331375000.0 and parameters: {'max_depth': 10, 'min_samples_split': 127, 'min_samples_leaf': 39, 'max_features': 0.6712378224164615, 'max_samples': 0.7659112571529955}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 03:31:27,952] Trial 43 finished with value: 332502500.0 and parameters: {'max_depth': 18, 'min_samples_split': 298, 'min_samples_leaf': 26, 'max_features': 0.4598484671840225, 'max_samples': 0.7988532003424618}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 03:35:31,272] Trial 44 finished with value: 327965000.0 and parameters: {'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 53, 'max_features': 0.5497393292213093, 'max_samples': 0.7208579971347217}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 03:40:04,446] Trial 45 finished with value: 336572500.0 and parameters: {'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 135, 'max_features': 0.512905610227402, 'max_samples': 0.8304179625344079}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 03:43:29,715] Trial 46 finished with value: 302582500.0 and parameters: {'max_depth': 5, 'min_samples_split': 22, 'min_samples_leaf': 12, 'max_features': 0.6037224788472317, 'max_samples': 0.8046687832866588}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 03:47:52,575] Trial 47 finished with value: 338387500.0 and parameters: {'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 69, 'max_features': 0.3880124893812052, 'max_samples': 0.6597048329420566}. Best is trial 35 with value: 348645000.0.

In [10]:
# PARA SEGUIR EJECUTANDO SI SE DETUVO 

storage_name = "sqlite:////Users/carof/Downloads/DENICOLAY/optimization_rf.db"
study_name = "exp_401_random-forest-opt-vFE13sept"

# 1. Cargar el estudio existente
study = optuna.load_study(
    study_name=study_name,
    storage=storage_name,
)

# 2. Calcular cuántos trials faltan para llegar a la meta (ej. 100 trials totales)
TOTAL_TRIALS = 100
completed_trials = len(study.trials)
remaining_trials = max(0, TOTAL_TRIALS - completed_trials)

print(f"Trials completados: {completed_trials} | Restantes: {remaining_trials}")

# 3. Continuar la optimización si restan trials
if remaining_trials > 0:
    study.optimize(objective, n_trials=remaining_trials)

Trials completados: 49 | Restantes: 51

[I 2026-09-14 14:10:34,162] Trial 49 finished with value: 324280000.0 and parameters: {'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 46, 'max_features': 0.4521121154128448, 'max_samples': 0.9822964743632623}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 14:25:20,430] Trial 50 finished with value: 327910000.0 and parameters: {'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 23, 'max_features': 0.6455296089428854, 'max_samples': 0.8370413665759139}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 14:32:59,296] Trial 51 finished with value: 327387500.0 and parameters: {'max_depth': 20, 'min_samples_split': 94, 'min_samples_leaf': 85, 'max_features': 0.3292895534070893, 'max_samples': 0.7514506734177663}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 14:43:38,618] Trial 52 finished with value: 327085000.0 and parameters: {'max_depth': 15, 'min_samples_split': 244, 'min_samples_leaf': 139, 'max_features': 0.49780703240783464, 'max_samples': 0.7166061536280076}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 15:03:39,367] Trial 53 finished with value: 325957500.0 and parameters: {'max_depth': 21, 'min_samples_split': 31, 'min_samples_leaf': 33, 'max_features': 0.596281211739777, 'max_samples': 0.8794526521300121}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 18:11:35,298] Trial 54 finished with value: 326315000.0 and parameters: {'max_depth': 24, 'min_samples_split': 58, 'min_samples_leaf': 63, 'max_features': 0.6062428019079712, 'max_samples': 0.910445010152926}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 18:32:25,588] Trial 55 finished with value: 328322500.0 and parameters: {'max_depth': 18, 'min_samples_split': 28, 'min_samples_leaf': 46, 'max_features': 0.5850060528593114, 'max_samples': 0.9536357560596297}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 18:35:39,718] Trial 56 finished with value: 266832500.0 and parameters: {'max_depth': 3, 'min_samples_split': 37, 'min_samples_leaf': 187, 'max_features': 0.5534270211929164, 'max_samples': 0.850527822693298}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 18:49:28,383] Trial 57 finished with value: 332090000.0 and parameters: {'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 55, 'max_features': 0.6429685142553523, 'max_samples': 0.8783815248080769}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 19:20:49,366] Trial 58 finished with value: 326535000.0 and parameters: {'max_depth': 7, 'min_samples_split': 161, 'min_samples_leaf': 28, 'max_features': 0.6745797330035596, 'max_samples': 0.927009778358259}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 19:29:01,556] Trial 59 finished with value: 313555000.0 and parameters: {'max_depth': 13, 'min_samples_split': 23, 'min_samples_leaf': 14, 'max_features': 0.5157621930771359, 'max_samples': 0.8053536321326143}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 19:30:52,753] Trial 60 finished with value: 327057500.0 and parameters: {'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 76, 'max_features': 0.09914916809943419, 'max_samples': 0.9980667200082827}. Best is trial 35 with value: 348645000.0.
[I 2026-09-14 19:37:50,673] Trial 61 finished with value: 329395000.0 and parameters: {'max_depth': 23, 'min_samples_split': 18, 'min_samples_leaf': 146, 'max_features': 0.4428728628430823, 'max_samples': 0.826086354605543}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 09:28:58,945] Trial 62 finished with value: 256272500.0 and parameters: {'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.5677630524735118, 'max_samples': 0.7826021682685059}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 09:39:36,863] Trial 63 finished with value: 332612500.0 and parameters: {'max_depth': 14, 'min_samples_split': 13, 'min_samples_leaf': 94, 'max_features': 0.39668390640473816, 'max_samples': 0.7416944819873967}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 09:51:01,518] Trial 64 finished with value: 327387500.0 and parameters: {'max_depth': 14, 'min_samples_split': 49, 'min_samples_leaf': 114, 'max_features': 0.47312226321327977, 'max_samples': 0.6669255260635975}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 10:02:45,273] Trial 65 finished with value: 330000000.0 and parameters: {'max_depth': 12, 'min_samples_split': 47, 'min_samples_leaf': 200, 'max_features': 0.5303566466155492, 'max_samples': 0.6935065620238736}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 10:16:45,359] Trial 66 finished with value: 324417500.0 and parameters: {'max_depth': 15, 'min_samples_split': 70, 'min_samples_leaf': 78, 'max_features': 0.478574577435813, 'max_samples': 0.7674428057624831}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 10:35:15,875] Trial 67 finished with value: 331567500.0 and parameters: {'max_depth': 16, 'min_samples_split': 39, 'min_samples_leaf': 39, 'max_features': 0.4865410316789748, 'max_samples': 0.8696933434312355}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 10:59:15,163] Trial 68 finished with value: 335005000.0 and parameters: {'max_depth': 13, 'min_samples_split': 28, 'min_samples_leaf': 160, 'max_features': 0.6202182875751071, 'max_samples': 0.7311070899740251}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 11:18:15,850] Trial 69 finished with value: 321035000.0 and parameters: {'max_depth': 17, 'min_samples_split': 95, 'min_samples_leaf': 93, 'max_features': 0.5559820753322159, 'max_samples': 0.4005226104054467}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 12:21:15,422] Trial 70 finished with value: 326260000.0 and parameters: {'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 58, 'max_features': 0.5876679041819665, 'max_samples': 0.8411786843505913}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 12:35:22,045] Trial 71 finished with value: 321145000.0 and parameters: {'max_depth': 19, 'min_samples_split': 33, 'min_samples_leaf': 116, 'max_features': 0.4341878854715172, 'max_samples': 0.81635987220004}. Best is trial 35 with value: 348645000.0.
[I 2026-09-15 12:49:03,992] Trial 72 finished with value: 338717500.0 and parameters: {'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 41, 'max_features': 0.5265027125843946, 'max_samples': 0.8985325623410779}. Best is trial 35 with value: 348645000.0.
[W 2026-09-15 12:49:23,681] Trial 73 failed with parameters: {'max_depth': 11, 'min_samples_split': 55, 'min_samples_leaf': 32, 'max_features': 0.2854641449952749, 'max_samples': 0.7063491393304288} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\carof\AppData\Local\Temp\ipykernel_18908\1831169487.py", line 33, in objective
    model.fit(X_train, y_train)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\ensemble\_forest.py", line 486, in fit
    trees = Parallel(
    ...<2 lines>...
        prefer="threads",
    )(
        delayed(_parallel_build_trees)(
    ...<12 lines>...
        for i, t in enumerate(trees)
    )
  File "c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ~~~~^^^^^^^^
  File "c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "c:\Users\carof\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\parallel.py", line 1800, in _retrieve
    time.sleep(0.01)
    ~~~~~~~~~~^^^^^^
KeyboardInterrupt
[W 2026-09-15 12:49:23,889] Trial 73 failed with value None.

KeyboardInterrupt: